package com.demos.param.ashtrestoant.DB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demos.param.ashtrestoant.DB.Order;
import com.demos.param.ashtrestoant.DB.productList;

import com.demos.param.ashtrestoant.DB.OrderDao;
import com.demos.param.ashtrestoant.DB.productListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig productListDaoConfig;

    private final OrderDao orderDao;
    private final productListDao productListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        productListDaoConfig = daoConfigMap.get(productListDao.class).clone();
        productListDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        productListDao = new productListDao(productListDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(productList.class, productListDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        productListDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public productListDao getProductListDao() {
        return productListDao;
    }

}
